set.seed(1234)
gender=sample(x=c('Male','Female'),size = 1000,replace = T,prob = c(0.5,0.5))
buy=sample(x=c('Buy','Notbuy'),size=1000,replace = T,prob=c(0.5,0.5))
married=sample(x=c('married','single'),size=1000,replace=T,prob = c(0.3,0.7))
age=ceiling(runif(1000,22,30))
course=sample(x=c('Phd','MBA','BBA'),size=1000,replace=T,prob=c(0.3,0.4,0.3))
students=data.frame(buy,gender,married,age,course)
head(students)
ctree=rpart(buy~.,data=students)
ctree
rpart.plot(ctree,nn=T,cex = 1,under=F, shadow=c('yellow', 'magenta','light green'))
names(students)

(ndata1=data.frame(gender='Male',age=22,course='MBA',married='single'))
(p1=predict(ctree,newdata = ndata1,type='class'))
(p2=predict(ctree,newdata=ndata1,type='prob'))

printcp(ctree)
ctree2=rpart(buy~.,data = students,cp= 0.00412371)
ctree2
rpart.plot(ctree2,nn=T,cex=.8)
printcp(ctree2)
(ndata2=data.frame(gender=c('Female','Male'),age=c(22,30),course=c('BBA','MBA'),married=c('single','married')))
(p1=predict(ctree2,newdata = ndata2,type='class'))
(p2=predict(ctree2,newdata=ndata2,type='prob'))
